name: 'SonarQube Report'
description: 'Gera report do Sonar na log, summary e PR'

inputs:
  sonar-analysis-id:
    description: "SonarQube Analysis id"
    required: true
  sonar-project-key:
    description: "SonarQube project key"
    required: true
  sonar-host-url:
    description: "SonarQube server URL"
    required: true
  sonar-token:
    description: "SonarQube token for retrieving quality gate result"
    required: true
  github-token:
    description: "GitHub Token for commenting on the pull request"
    required: false

runs:
  using: 'node20'
  main: 'src/index.js'
